//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Utility
{
	public static float clampAngle(float angle, float leftClamp, float rightClamp) {
		if (angle < leftClamp) return leftClamp;
		if (angle > rightClamp) return rightClamp;
		return angle;
	}
}

